#+TITLE: Blockchain Σημειώσεις
#+AUTHOR: Bill Xykis
#+DATE:
#+MACRO: color @@html:<font color="$1">$2</font>@@ 

* Sos part1
23.40 part1

** _Διαφορά ανάμεσα σε permissioned και permissionless δίκτυα_

   *2 τύποι blockchain*
  
*** Permissioned 
    
Μόνο συγκεκριμένοι χρήστες έχουν την δυνατότητα read και write στο δίκτυο.
Κατάλληλο για επιχειρήσεις και κλάδους που θέλουν να αποκρύψουν στοιχεία απο το κοινό ή να έχουν μόνο συγκεκριμένους χρήστες. Τα permissioned networks γίνονται όλο και πιο δημοφιλή.

 /Θετικά:/
 + Είναι γρήγορα 
 + Σκεηλάρουν καλύτερα
 + Παραμετροπιούνται πιο εύκολα
   
 /Αρνητικά:/
 + Δεν είναι πραγματικά decentralized
 + Μικρή ανωνυμία
 + Μπορεί αν απαιτείται KYC
   
*** Permissionless
    
Ανοικτό για όλους (read & write). Ο κάθε χρήστης μπορεί να κατεβάσει το ledger στον υπολογιστή του και να δουλέψει επάνω σε αυτό ενεργά. Δεν χρειάζεται KYC, δηλαδή να δώσει στοιχεία για τον εαυτό του. Είναι πραγματικά decentralized. Κατάλληλα για digital currencies που χρειάζονται wide adoption.

 /Θετικά:/
 * Truly decentralized
 * High security
 * Δεν χρειάζεται ταυτοποίηση για να το χρησιμοποιήσει κάποιος

 /Αρνητικά:/
 * Είναι αργά
 * Δεν σκεηλάρουν εύκολα
 * Δεν κάνει για επιχειρήσεις που θέλουν να κρατήσουν μυστικά της επιχείρησης

** _Πως γίνονται published τα blocks_
*** Αρχιτεκτονική blockchain
*** Τι ειναι transaction
    [[https://en.bitcoin.it/wiki/Transaction][Transaction]] είναι η μεταφορά κάποιου ποσού bitcoin (μονάδα μέτρησης satotshi). To input adress είναι του sender και το output του receiver. 
*** Nonce (τι χρηστικότητα έχει)
    [[https://www.investopedia.com/terms/n/nonce.asp][Nonce]] or "number only used once" είναι ένας αριθμός, οπου οι miners πρέπει να λύσουν, για να βάλουν το block τους στο blockchain.
*** Πως λειτουργέι η ασυμμετρη κρυτπογράφηση
   [[https://hackernoon.com/asymmetric-cryptography-in-blockchains-d1a4c1654a71][Η ασύμμετρη κρυπτογράφηση]] λειτουργέι με την δημιουργία του public και private key. Τα δύο κλειδιά έχουν μεταξύ τους ασύμμετρη σχέση και μπορούν να αποκρυπτογράφησουν το καθένα, τα κρυπτογραφημένα μηνύματα του άλλου. Το private key πρέπει να μένει κρυφό, επειδή ουσιαστικά αποδηκνύει την ταυτότητα του χρήστη. Το public key μπορεί να διαμοιραστεί. Στο bitcoin οικοσύστημα, η κάθε διεύθυνση είναι ένα public key, και για να μπορέσουμε να την χρησιμοποιήσουμε χρειαζόμαστε το private key της, χωρίς αυτό δεν μπορούμε να κάνουμε τίποτα.
   
   Για παράδειγμα, η Alice θέλει να στείλει στον Bob ένα κρυπτογραφημένο μήνυμα και τυατόχρονα το public key σε κρυπογραφημένη μορφή, ώστε ο Bob να μπορέσει να διαβάσει το μήνυμα της Alice. Αρχικά η Alice θα πει στον Bob, να δημιουργήσει ένα ζευγος από public και private keys και να της στείλε το public key του. Αφού γίνουν όλα αυτά, η Alice θα γράψει το μήνυμα, μαζί με το public key της κσι θα τα κρυπτογραφήσει με το public key του Bob και θα τα στείλει τον Bob. Έπειτα ο Bob με το private key του αποκρυπτογραφήσει το εισερχόμενο κείμενο, θα αποκτήσει πρόσβαση στο publi key της Alice και θα αποκρυπτογραφήσει και το μήνυμα της. 
*** Λιγα λόγια για consensus
    [[https://www.investopedia.com/terms/c/consensus-mechanism-cryptocurrency.asp][Ο consensus]] μηχανισμός είναι απαραίτητος για να έρθουν σε συμφωνία τα nodes για το state του blockchain. Αποτελείται απο συγκεκριμένους κανόνες και κάθε block και transaction πρέπει να τους ακουλουθεί. Αν δεν τους ακολουθεί, τότε τα full nodes το απορρίπτουν. Για να αλλάξουν οι consensus κανόνες πρέπει να γίνει hard fork.
*** Τι σημαίνει μπλοκς
    Ένα block περιέχει όλα ή ένα κομμάτι από τα πρόσφατα transactions. Επίσης το πρώτο transaction σε ένα block είναι το address του miner που εισήγαγε το προηγόυμενο block. Από την στιγμή που θα μπει ένα block στο blockchain δεν μπορεί να αφαιρεθεί, ούτε να τροποποιηθεί. Μπορούμε σαν αναλογία να σκεφτούμε το blockchain σαν το αρχείο συναλλαγών μιας τράπεζας και το block σαν μια συγκεκριμένη συναλλαγή μέσα στο αρχείο. 
*** _How blocks are chained together_
    0.13.42
    Μέσα σε ένα μπλοκ περιλαμβάνονται διάφορες πληροφορίες. Στο block header υπάρχει το hash του προηγούμενο header, ένα timestamp και το nonce. Επίσης υπάρχουν και transactions.

    Τα transactions που δουλεύουν τα nodes δεν είναι απαραίτητα τα ίδια, κάθε node μπορεί να επιλέξει ποια transactions θέλει από ενα transaction pool
Εικόνα 0.17.24

    Τα nodes του δικτύου προσπαθούν να μαντέψουν την λύση με εναν αλγόριθμο χασαρίσαμτος ώστε να βρούνε ένα συγκεκρίμενο output που ζητάει το σύστημα.
** Τί ειναι τα smart contracts
   [[https://www.youtube.com/watch?v=ZE2HxTmxfrI][Σχετικό βιντεάκι]]
   Τα smart contracts βρίσκονται στο blockchain και για αυτό το λόγο έχουν την ιδιότητα, πως είναι αμετάβλητα. Τα smart contracts είναι τα συμβόλαια του ψηφιακύ κόσμου. Όταν οι προυποθέσεις του έξπνου συμβολάιου εκλπηρώνονται τότε το smart contract εκτελείται. Χάρις τα smart contracts δεν χρειάζονται μεσάζοντες, για να ελέξουν αν τηρούνται οι προυποθέσεις των συναλλαγούντων.
** Τι πρέπει να έχει ενα blockchain:
 1. multiple writers
 2. minimal trust
 3. no intermidiates
 4. transaction depedencies
 5. shared repository

* SOS part2

** _Μηχανισμοί συναίνεσης (consensus mechanics)_
*** Proof of work
    3.45
    To proof of work απαιτεί υπλογιστική ισχύ απο τους miners για να βρούνε το επόμενο hash. Όση περισσότερη υπολογιστική ισχυ έχουν, τόσες περισσότερες πιθανότητες να βρόυνε το σωστό hash. Όποιος miner βρει το hash κερδίζει ένα reward. Πλέον έχουν σχηματιστεί mining pool, ώστε να αυξηθεί η υπολογιστική ισχύ και οι miners του pool διαμοιράζονται μεταξύ τους το reward/
    
    Θετικά:
    + Θεωρείται πιο ασφαλές απο PoS
    + Προστασία απο DDos attack
    + Όσα λεφτά και να έχει κάποιος δεν μπορεί να επηρεάσει το δίκτυο, αν δεν έχει υπολογιστική ισχύ

    Αρνητικά:
    + Ευκολότερη η επίθεση 51% σε σχέση με PoS, αν ενωθούν τα mining pools
    + Πολύ ενεργοβόρο
    + Το χρήμα στο χρήμα, όσο περισσότερο υπολογιστική ισχύ έχεις κάποιος, τόσες πιο πολλες φορές θα κερδίζει

*** Proof of stake
    4.00
    Proof of stake o κάθε "miner" βάζει σαν stake στην άκρη ενα χρηματικό ποσό. Στην συνέχεια ενας αλγόριθμος διαλέγει τον επόμενο validator, για το μπλοκ. Οσο μεγαλύτερο είναι το ποσο που έχει βάλει ο πιθανός validator τόσες περισσότερες οι πιθανότητες να επιλεχθεί. Θεωρείται οικολογική λύση για trustless transactions. Για να κάνει κάποιος 51% attack, θα χρειαζόταν υπέρογκο ποσό χρημάτων.  
**** ΘΈΜΑΤΑ ασφάλειας
     double voting (κάθε blockchain έχει βρει δικό του τρόπο αντιμετώπισης για το double voting)
     Long range attack (αν κάποιος ξεκινήσει από το genesis block και έχει το 1% του stake θα μπορούσε να φτιάξει τα επόμενα blocks)
     Weak subjectivity (όταν ένα node που μπαίνει για πρώτη φορά στο δίκτυο ή ηταν offline για πολύ καιρό έχει να διαλέξει ποιο είναι το σωστό chain)
*** Proof of activity
    Συνδιασμός των 2 προηγούμενων μηχανισμών
*** PBFT
    6.30
*** _Θεματα ασφάλειας_
*** Πιθανές ερωτήσεις
    * Πείτε 3 θέματα ασφάλειας που μπορεί να έχει το PoS
    * Βασικά χαρακτηριστικά PoW

*** Διάφορες επιθέσεις σε pοs και pow
    Μπορεί το malicious node να κάνει selfish mining (να βρεί τα μπλοκς αλλά να μην τα κάνει απευθειάς publish).

** Forks 

9.50
*** _Soft forks_
    Τα soft forks αλλάζουν το προτόκολου του blockchain με backward compatibilty δυνατότητα. Δηλάδη αν θεωρήσουμε το fork σαν τρόπο update του blockchain, όσα nodes δεν ακολουθήσουν το συγκεκριμένο update ή fork, θα μπορούν να συνεχίσουν να συνεργάζονται στo ίδιο chain με τα nodes που ακολούθησαν το fork.
*** _Hard forks_
    Το hard fork από την άλλη αλλάζει το προτόκολο με τέτοιον τρόπο, ώστε τα nodes που δεν θα ακολουθήσουν, δεν μπορόυν να συνεργαστούν με τα nodes που το ακολούθησαν. Σαν αποτέλεσμα έχει ή ολα τα nodes να κανουν το φορκ ή να δημιουργούνται 2 chains.
*** _Conflict resolutions_
    11.15
    longest chain
    To conflict resolution είναι όταν σε PoW consensus δυο miners κάνουν publish ταυτόχρονα ενα block. Σε αυτήν την περίπτωση θα δημιργηθούν 2 πιθανά chains και το valid chain θα γίνει το μακρύτερο, δηλαδή όποιο αναπτυχθέι πιο γρήγορα. Τα transactions του invalid block ξαναγυρνάνε στο pool. 

https://www.tutorialspoint.com/blockchain/blockchain_resolving_conflicts.htm
*** Τρόπος
*** Πιθανες ερωτήσεις
    _Διαφορά μεταξύ soft και hard_

** Εμπειρική ερώτηση: Εφαρμογή blockchain
Τι είδος blockchain και τι περιορισμούς θα είχα για blockchain σε τράπεζα

* Dump
Το bitcoin εχει volatility και είναι μη πληθοριστικό νόμισμα. 

** Nodes
Δεν εκτελούν όλα τα nodes το ίδιο πράγμα. Lightweight μόνο μεταφέρουν πληροφορία. 

** Αρχιτεκτονικη 
0:11:00



